"""
Seed data for golden sayings (quotes).
"""
QUOTES = [
    ("Whether you think you can, or you think you can't – you're right.", "Henry Ford", "United States"),
    ("The mind is everything. What you think you become.", "Buddha", "Nepal/India"),
    ("Everything can be taken from a man but one thing: the last of the human freedoms—to choose one's attitude in any given set of circumstances.", "Viktor Frankl", "Austria"),
    ("Self-discipline matters more than success. Lasting respect is earned through conduct, not display.", "Confucius", "China"),
    ("Fall seven times, stand up eight.", "Japanese Proverb", "Japan"),
    ("Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", "Rumi", "Persia (Iran)"),
    ("The secret of getting ahead is getting started.", "Mark Twain", "United States"),
    ("When the way is straight, I push on; when it is crooked, I put up with it. Old age and early death, failure and success, all these come naturally and of themselves.", "Attributed to Yang Chu", "China"),
    ("Dripping water wears away stone.", "Chinese Proverb", "China"),
    ("It is not primarily our physical selves that limit us but rather our mindset about our physical limits.", "Ellen J. Langer", "United States"),
    ("Everyone must choose one of two pains: The pain of discipline or the pain of regret.", "Jim Rohn", "United States"),
    ("The most important opinion you'll ever have is the one you hold of yourself.", "Denis Waitley", "United States"),
    ("Bondage and Liberation are of the mind alone.", "Sri Ramakrishna", "India"),
    ("People who don't know themselves criticize others from the point of view of their own ignorant selves.", "Suzuki Shōsan", "Japan"),
    ("When your psychological state is bad, discipline will just make it worse. Discipline is a matter of fortifying potential, so it is imperative to avoid depletion.", "Suzuki Shōsan", "Japan"),
    ("The heights by great men reached and kept were not attained by sudden flight, but they, while their companions slept, were toiling upward in the night.", "Henry Wadsworth Longfellow", "United States"),
    ("It is during our darkest moments that we must focus to see the light.", "Aristotle", "Greece"),
    ("You are the master of your destiny. You can influence, direct and control your own environment.", "Napoleon Hill", "United States"),
    ("If you chase two rabbits, you will catch neither.", "Japanese Proverb", "Japan"),
    ("Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.", "Lao Tzu", "China"),
    ("The only person who never makes mistakes is the person who never does anything.", "Denis Waitley", "United States"),
    ("If there is no wind, row.", "Chinese Proverb", "China"),
    ("Discipline is what converts noise to music. Disciplining the mind will allow students to do wonders in life and bring out their best and deepest potential.", "Alok Chopra", "India"),
    ("I learned that courage was not the absence of fear, but the triumph over it.", "Nelson Mandela", "South Africa"),
    ("Many of life's failures are people who did not realize how close they were to success when they gave up.", "Thomas Edison", "United States"),
    ("Every step is on the path.", "Lao Tzu", "China"),
    ("We learn little from victory, much from defeat.", "Japanese Proverb", "Japan"),
    ("A gem is not polished without friction, nor a man perfected without trials.", "Chinese Proverb", "China"),
    ("Our ability to handle life's challenges is a measure of our strength of character.", "Les Brown", "United States"),
    ("When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.", "Confucius", "China"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill", "United Kingdom"),
    ("The best time to plant a tree was twenty years ago. The second-best time is now.", "Chinese Proverb", "China"),
    ("Beware of your mind, and take responsibility for yourself.", "Suzuki Shōsan", "Japan"),
    ("Be yourself, compete with yourself and be the best version of yourself. Don't compete, don't do anything for returns. This is the path to a happy life.", "Alok Chopra", "India"),
    ("The most beautiful people we have known are those who have known defeat, known suffering, known struggle, known loss, and have found their way out of the depths.", "Elisabeth Kübler-Ross", "Switzerland/United States"),
    ("Joys and sorrows are time born and cannot last. Therefore, do not be perturbed by them.", "Anandamayi Ma", "India"),
    ("Every action you take is a vote for the kind of person that you wish to become.", "James Clear", "United States"),
    ("The taller the bamboo grows, the lower it bends.", "Japanese Proverb", "Japan"),
    ("Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along.", "Napoleon Hill", "United States"),
    ("You can tell whether a man is clever by his answers. You can tell whether a man is wise by his questions.", "Naguib Mahfouz", "Egypt"),
    ("One day of endeavour is better than a hundred years of sloth.", "Buddha", "Nepal/India"),
    ("The key is to keep company only with people who uplift you, whose presence calls forth your best.", "Epictetus", "Greece/Rome"),
    ("A man who does not work, shall not eat.", "Indian Proverb", "India"),
    ("Patience is the key to paradise.", "Indian Proverb", "India"),
    ("All life is an experiment. The more experiments you make the better.", "Ralph Waldo Emerson", "United States"),
    ("Sweat is the perfume of success.", "Indian Proverb", "India"),
    ("Don't let the fear of striking out hold you back.", "Babe Ruth", "United States"),
    ("Mind is a sea of emotions, with likes and dislikes. It functions on desire. Intellect, on the other hand, discriminates between right and wrong.", "Alok Chopra", "India"),
    ("Better to light one small candle than to curse the darkness.", "Chinese Proverb", "China"),
    ("The axe forgets; the tree remembers.", "Indian Proverb", "India"),
]
